### ISSUE TITLE
Anything for Samsung phone

### ISSUE THREAD

**Issue by Philliec459** [eaniemey/gcpr-onevalley-covid19-ios#1]
I live in CB and would love to get on this, but it appears to be Apple. I have a mac and iPad but recently bought Samsung phone

**Comment by eaniemey** [comment]
Hi Craig. We are working on an Android reference version but it is not ready to post yet. I'll update this thread when it is posted.

**Comment by Philliec459** [comment]
Please do. I am all in favor with what you all are doing. I participated in the Kaggle contest for COVID-19. I built my own predictive models for Confirmed Cases and Deaths (getting data from Johns Hopkins) by countries or by US state. Unfortunately, it looks like we are in for a new wave, and we need to be using tools like yours to get ready. I have been following BlueDot out of Toronto and I think we need to be anonymously tracking general population movements, social interactions, visitor hotel registrations ….. 

The simple image below shows that we are surrounded by the new wave states, and many of them will be coming here this summer. 

I would be glad to help if there is anything that I can do. I am doing a fair amount of Object Detection and am experimenting with a NVIDIA Jetson Xavier NX. We could use IR to detect people with temperatures, violations of social distancing by getting too close …. 






Best Regards, 
 
_______________________________
 
E. Craig Phillips
CEO and Chief Petrophysicist
Crested Butte Petrophysical Consultants
 







459 Cisneros Lane
Crested Butte, CO 81224
USA
Office: +1 970-343-0730
Mobile: +1 970-343-0730
email: craig@cbpetro.com
Website: www.cbpetro.com
GitHub: https://github.com/Philliec459



The information contained in this electronic message is confidential, it constitutes a profesional and/or industrial secret in terms of the current legislation, and is intended for its recipient only. If you receive this message by mistake or if you are not the recipient thereof, please notify the sender and destroy it.

La informacion contenida en este mensaje de datos es confidencial, constituye un secreto industrial y/o profesional en terminos de la legislacion vigente y se encuentra dirigida exclusivamente al destinatario indicado en dicho mensaje. Si usted recibe esta informacion por error o si usted no es el destinatario del mensaje, favor de notificar al emisor, y destruyalo.

On Jun 24, 2020, at 8:34 AM, Erik Niemeyer <notifications@github.com> wrote:


Hi Craig. We are working on an Android reference version but it is not ready to post yet. I'll update this thread when it is posted.
